### ISSUE TITLE
Bumping major version number on dependency without bumping major version number on module.

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/mbed-hal-nrf51822-mcu#21]
This commit breaks code: 

https://github.com/ARMmbed/mbed-hal-nrf51822-mcu/commit/c111b01bd9b7eed70995f9b2c79233763e0ecef1

Patch versions are for patches, minor versions are for backwards compatible features. This change is API breaking and requires a major version bump.

**Comment by 0xc0170** [comment]
:+1:

Marcus, what can we do now?

**Comment by marcuschangarm** [comment]
1. delete release v1.0.5 in registry
2. delete tag v1.0.5 on github
3. bump major version
4. release v2.0.0

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1173

**Comment by 0xc0170** [comment]
@marcuschangarm I believe this was resolved, please close if true

**Comment by autopulated** [comment]
Much better to release a fixed 1.0.6 reverting the change than delete something from the registry!

**Comment by rgrover** [comment]
@autopulated: We have already released a 1.0.6. Not sure if you noticed.
