### ISSUE TITLE
Publish to yotta?

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/mbed-hal-nrf51822-mcu#25]
This seems to be the last dep missing from yotta for ble-examples to build publicly. Is there anything holding up its publishing?

**Comment by rgrover** [comment]
@jacobrosenthal no. I'm surprised this isn't in the public registry. This will be resolved shortly.

**Comment by rgrover** [comment]
@jacobrosenthal: if you search for 'mcu' on yotta.mbed.com, you'll find that this module has been published.

Could you please delete the subflolder yotta_modules in your top level application module and retry?

**Comment by rgrover** [comment]
I'm sorry, I shouldn't have closed this issue myself. Please close this when you're able to find this module through a 'yotta install'.

**Comment by jacobrosenthal** [comment]
Confirmed. Thanks.
