### ISSUE TITLE
Strange circular Dependency

### ISSUE THREAD

**Issue by dhofstetter** [ARMmbed/mbed-hal-nrf51822-mcu#49]
As posted already here: ARMmbed/mbed-hal#79

There is a strange dependency issue, and also there is a fix that can be used. Maybe this should be included to the next release.

BR Daniel

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2452

**Comment by dhofstetter** [comment]
Just for my personal Information, what does the **mirrored** label mean? And what is the meaning of the **ARM Internal Ref**?

BR Daniel

**Comment by 0xc0170** [comment]
That the issue was mirrored to internal services we use. I'll send PR fixing this issue

**Comment by dhofstetter** [comment]
Thanks, hopefully this helps a lot others too. Because if you are new to the mbed Project world the errors that are given through yotta by having this strange dependency issue are hardly to understand :+1: 

Closed because it's fixed for me
